cobc -x BREADWICH.cob
cobc -m ADD-INGREDS.cob
cobc -m addsupman.cob
cobc -m ADDSUPPCSV.COB
cobc -m CALENDAR.cob
cobc -m CAMADD.cob
cobc -m CAMDELETE.cob
cobc -m CAMEDIT.cob
cobc -m CAMVIEW.cob
cobc -m CATEADD.cob
cobc -m CATEDEL.COB
cobc -m CATEEDIT.COB
cobc -m CATEGORIES.cob
cobc -m CATEVIEW.cob
cobc -m INGREDIENTS.COB
cobc -m MAIN-INGREDS.COB
cobc -m MODIFY-INGREDS.cbl
cobc -m REMOVE-INGREDS.cbl
cobc -m SCHOOLS.COB
cobc -m SCM-ADD.cbl
cobc -m SCM-DELETE.cbl
cobc -m SCM-EDIT.cbl
cobc -m SCM-VIEW.cbl
cobc -m SUPPADD.cob
cobc -m SUPPDEL.COB
cobc -m SUPPEDIT.COB
cobc -m suppliers.cob
cobc -m SUPPVIEW.COB
cobc -m rsomain.cob
cobc -m rsoregister.cob
cobc -m rsoreport.cob
cobc -m rsosearch.cob
cobc -m CAMSEARCH.COB
cobc -m SEARCH-INGREDS.COB
cobc -m sr-add.cbl
cobc -m sr-search.cbl
cobc -m srmain.cbl
cobc -m main-ris.cbl
cobc -m record-ris.cbl
cobc -m report-ris.cob
cobc -m search-ris.cob
cobc -m VIEW-INGREDS.cbl
cobc -m SR-REPORT.cbl